experiment: cifar100_
epochs: 100
output_dir: save
resume: null
save_interval: 10

optimizer:
  type: Adam
  args:
    lr: 3.0e-5

scheduler:
  type: CosineAnnealingLR
  args:
    T_max: 100

dataset:
  type: CIFAR100
  args:
    root: /data/baole/cifar100
    download: True
  train_transforms:
    - type: ToTensor
    - type: Resize
      args:
        size: [ 256, 256 ]
    - type: RandomCrop
      args:
        size: 224
    - type: RandomHorizontalFlip
    - type: Normalize
      args:
        mean: [ 0.5074,0.4867,0.4411 ]
        std: [ 0.2011,0.1987,0.2025 ]
  test_transforms:
    - type: ToTensor
    - type: Resize
      args:
        size: [ 224, 224 ]
    - type: Normalize
      args:
        mean: [ 0.5074,0.4867,0.4411 ]
        std: [ 0.2011,0.1987,0.2025 ]
  train_loader:
    batch_size: 64
    shuffle: True
    num_workers: 16
    pin_memory: True
  test_loader:
    batch_size: 64
    shuffle: False
    num_workers: 16
    pin_memory: True

model:
  type: ViT
  args:
    image_size: 224
    patch_size: 32
    num_classes: 100
    dim: 1024
    depth: 6
    heads: 16
    mlp_dim: 2048
    dropout: 0.1
