experiment: cifar10
epochs: 100
output_dir: save
resume: null
save_interval: 10

optimizer:
  type: Adam
  args:
    lr: 0.0003
    weight_decay: 0.1

scheduler:
  type: CosineAnnealingLR
  args:
    T_max: 100

dataset:
  type: CIFAR10
  args:
    root: /data/baole/cifar10
    download: True
  train_transforms:
    - type: ToTensor
#    - type: Resize
#      args:
#        size: [ 256, 256 ]
    - type: RandomHorizontalFlip
    - type: Normalize
      args:
        mean: [ 0.5074,0.4867,0.4411 ]
        std: [ 0.2011,0.1987,0.2025 ]
  test_transforms:
    - type: ToTensor
#    - type: Resize
#      args:
#        size: [ 256, 256 ]
    - type: Normalize
      args:
        mean: [ 0.5074,0.4867,0.4411 ]
        std: [ 0.2011,0.1987,0.2025 ]
  train_loader:
    batch_size: 1024
    shuffle: True
    num_workers: 16
    pin_memory: True
  test_loader:
    batch_size: 1024
    shuffle: False
    num_workers: 16
    pin_memory: True

model:
  type: ViT
  args:
    image_size: 32
    patch_size: 8
    num_classes: 10
    dim: 1024
    depth: 6
    heads: 16
    mlp_dim: 2048
    dropout: 0.1
