experiment: imagenet-m
epochs: 100
output_dir: save
resume: null
save_interval: 10

optimizer:
  type: Adam
  args:
    lr: 3.0e-5

scheduler:
  type: CosineAnnealingLR
  args:
    T_max: 100

dataset:
  type: ImageNet
  train:
    args:
      root: /data/baole/imagenet
      split: train
    transforms:
      - type: ToTensor
      - type: Resize
        args:
          size: [ 256, 256 ]
      - type: RandomCrop
        args:
          size: 224
      - type: RandomHorizontalFlip
      - type: Normalize
        args:
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
    loader:
      batch_size: 512
      shuffle: True
      num_workers: 16
      pin_memory: True
  test:
    args:
      root: /data/baole/imagenet
      split: val
    transforms:
      - type: ToTensor
      - type: Resize
        args:
          size: [ 224, 224 ]
      - type: Normalize
        args:
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
    loader:
      batch_size: 64
      shuffle: False
      num_workers: 16
      pin_memory: True

model:
  type: ViT
  args:
    image_size: 224
    patch_size: 32
    num_classes: 1000
    dim: 1024
    depth: 6
    heads: 16
    mlp_dim: 2048
    dropout: 0.1
